# Generated by Django 6.0.7 on 2026-07-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('receipt_header', models.TextField(default='Thank you for shopping with SmartPOS!')),
                ('receipt_footer', models.TextField(default='Please visit us again. Returns accepted within 7 days.')),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='authentication.business')),
            ],
        ),
    ]
